#!/bin/bash
# useful. thanks to http://www.commandlinefu.com/commands/view/10280/view-all-file-operator-expressions-for-any-file-test-stat#comment

o=abcdefghLkprsStuwxOGN;
echo $@;
for((i=0;i<${#o};i++));do
    c=${o:$i:1};
    test -$c $1 && help test | sed "/^ *-$c/!d;1q;s/^[^T]*/-$c /;s/ if/ -/";
done;
