" autoload pathogen
call pathogen#infect()

scriptencoding utf-8
set encoding=utf-8

set number
set tabstop=4 shiftwidth=4 expandtab
set guifont=Bitstream\ Vera\ Sans\ Mono\ 8

set cursorline

filetype plugin on
syntax enable

if has ('gui_running')
    set guioptions-=r  " no scrollbar on the right
    set guioptions-=l  " no scrollbar on the left
    set guioptions-=m  " no menu
    set guioptions-=T  " no toolbar
endif

if $COLORTERM == 'gnome-terminal' || $COLORTERM == 'xterm' || $COLORTERM == 'Terminal' || ! has("gui_running")
    set t_Co=256
    colorscheme gotham256
    AirlineTheme gotham256
else
    colorscheme gotham
    AirlineTheme gotham
endif

"source ~/.vim/plugin/imaps.vim

set hlsearch
set list listchars=trail:·,precedes:«,extends:»,tab:▸\
set ruler

"" nocompatible is important to be able to navigate with arrow keys in systems
" like freebsd and macos
set nocompatible
set backspace=indent,eol,start

autocmd FileType make set noexpandtab

map <Leader>b :MiniBufExplorer<cr>

" syntax hightlight configurations:
au BufRead,BufNewFile *.sql_diff set filetype=sql
" treat jinjai2 templates (as html)
au BufRead,BufNewFile *.jtml set filetype=html

let Tlist_Ctags_Cmd = "/usr/bin/ctags"
let Tlist_WinWidth = 50
map <F4> :TlistToggle<cr>

" syntastic options
let g:syntastic_check_on_open=1
" avoid syntastic checks for java files (too heavy)
let g:syntastic_mode_map = { 'mode': 'active',
                           \ 'active_filetypes': [],
                           \ 'passive_filetypes': ['java'] }

" pyflake options (automatic with F7)
autocmd BufWritePost *.py call Flake8()

" folding
set foldmethod=syntax
" all folds opened automatically
au BufRead * normal zR

" clear trailing withespaces
command CT %s/\ \+$//ge|%s/\t/    /gce

" highligh 120th column
set cc=120
hi ColorColumn ctermbg=black

" mouse on console
set mouse=a

map <F2> :NERDTreeToggle<CR>
nmap <F3> :TagbarToggle<CR>
nmap <F5> :GitGutterLineHighlightsToggle<CR>


