#!/bin/bash

PROJ_NAME=$1
echo "Creating python project skeleton for $PROJ_NAME"

T=`date`

mkdir $PROJ_NAME
mkdir $PROJ_NAME/doc
mkdir -p $PROJ_NAME/src/python/test
mkdir -p $PROJ_NAME/src/python/main
mkdir -p $PROJ_NAME/src/scripts
mkdir $PROJ_NAME/out

cat >$PROJ_NAME/TODO <<EOF
Todo for project $PROJ_NAME:

Bugs:

Core features:

Nice to have: 

Other:

EOF

cat >$PROJ_NAME/README <<EOF
Project $PROJ_NAME
==================

By: The Author
Created on: $T

Description:
============
This is project $PROJ_NAME. 
This is an autogenerated document.

Instalation:
============

- install.sh must be edited

Usage:
======

License:
========

Contact:
========

EOF

cat >$PROJ_NAME/pack.sh <<EOF
#!/bin/bash
echo Nothing comes for free...
echo -e "\033[01;33mTHIS WAS NOT YET IMPLEMENTED!\033[00m"

EOF
chmod -v +x $PROJ_NAME/pack.sh

cat >$PROJ_NAME/install.sh <<EOF
echo Nothing comes for free...
echo -e "\033[01;33mTHIS WAS NOT YET IMPLEMENTED!\033[00m"
#DEST_PATH=$HOME/bin/$PROJ_NAME
#cp -dpR $PROJ_NAME/src/
#echo Add $DEST_PATH to your PATH

EOF
chmod -v +x $PROJ_NAME/install.sh

