#!/usr/bin/env python
# filetype python

import os.path
import shutil
import sys

def perr (s):
    sys.stderr.write ("%s\n" % s)

def usage ():
    perr ('PROGNAME template_name path')

def main(args):

    if len (args) < 3:
        usage ()
        return -2

    verbose = len (args) > 3 and args [3] == '-v'

    template_name = args[1]
    target_name = args[2]

    if os.path.exists (target_name):
        perr ('target file %s already exists. aborting')
        return -3

    template_dir = os.path.expanduser ('~/.tpltouch/templates')

    if not os.path.isdir (template_dir):
        perr ('template directory %s either does not exist or is not a directory' % template_dir)

    template = os.path.join (template_dir, template_name)

    if not os.path.exists (template):
        perr ('template %s does not exists' % template_name)
        return -1

    if verbose:
        print 'From template %s create %s' % (template_name, target_name)

    shutil.copyfile (template, target_name)

    return 0

if __name__ == '__main__':
    import sys
    exit(main(sys.argv))
