# some variables for later use
local SYSTEM=$(uname -s)

# The following lines were added by compinstall
zstyle ':completion:*' completer _expand _complete _ignored
zstyle ':completion:*' list-colors ''
zstyle ':completion:*' list-prompt '%SAt %p: Hit TAB for more, or the character to insert%s'
zstyle ':completion:*' menu select=0
zstyle ':completion:*' select-prompt '%SScrolling active: current selection at %p%s'
zstyle :compinstall filename '/Users/john/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall
# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
bindkey -e
# End of lines configured by zsh-newuser-install

# MacPorts Installer addition on 2011-09-03_at_17:19:17: adding an appropriate PATH variable for use with MacPorts.
PATH=/opt/local/libexec/gnubin/:$PATH
PATH=/opt/local/bin:/opt/local/sbin:$PATH
PATH=/opt/local/lib/postgresql90/bin/:$PATH
PATH=$HOME/bin:$PATH
export PATH
# Finished adapting your PATH environment variable for use with MacPorts.

alias ls='ls --color'
alias l='ls -l'
alias lA='ls -lA'
alias lS='ls -lS'
alias lt='ls -lt'
alias irgrep='grep -irn'

alias diff='colordiff'
# support colored less
alias less='less -R'

if [[ $SYSTEM = 'Darwin' ]] ; then
    alias xargs='gxargs'
    alias find='gfind'

#    if [[ $HOST = 'hesse' ]] ; then
#        alias mvim='/Applications/MacPorts/MacVim.app/Contents/MacOS/MacVim'
#    fi
fi

if [[ $HOST = 'hesse' ]] ; then
    alias zssh='ssh -i ~/.ssh/zkeys/id_rsa'
    alias zscp='scp -i ~/.ssh/zkeys/id_rsa'
    alias python='python2.7'
fi

autoload colors
colors

case $HOST in
    hesse)
        hostcolor=blue
        ;;
    dresden)
        hostcolor=red
        ;;
    bataille)
        hostcolor=yellow
        ;;
    morgenthau)
        hostcolor=green
        ;;
    zlws-jj)
        hostcolor=magenta
        ;;
    *)
        hostcolor=gray
        ;;

esac

# oh-my-zsh stuff
ZSH=$HOME/Desktop/dev-tools/oh-my-zsh
source $ZSH/lib/git.zsh
source $ZSH/plugins/git/git.plugin.zsh
source $ZSH/plugins/svn/svn.plugin.zsh

ZSH_THEME_GIT_PROMPT_PREFIX="%{$reset_color%}%{$fg[white]%}["
ZSH_THEME_GIT_PROMPT_SUFFIX="]%{$reset_color%}"
ZSH_THEME_GIT_PROMPT_DIRTY="%{$fg[red]%}●%{$reset_color%}"
ZSH_THEME_GIT_PROMPT_CLEAN=""

ZSH_THEME_SVN_PROMPT_PREFIX="svn:("
ZSH_THEME_SVN_PROMPT_SUFFIX=")"
ZSH_THEME_SVN_PROMPT_DIRTY="%{$fg[red]%} ✘ %{$reset_color%}"
ZSH_THEME_SVN_PROMPT_CLEAN=" "

usercolor=$hostcolor
highlight=0

if [[ $EUID -eq 0 ]] ; then
    usercolor=red
    highlight=1
fi
setopt promptSubst
function precmd () {
    PS_USER_PART="%{$fg[$usercolor]%}%n%{$reset_color%}"
    if [[ $highlight -eq 1 ]] ; then
        PS_USER_PART="%U$PS_USER_PART"
    fi

    REPO_CUSTOM_STATUS=

    if [[ $(in_svn) -eq 1 ]]  ; then
        REPO_CUSTOM_STATUS="[$(svn_get_repo_name):$(svn_get_rev_nr)$(svn_dirty)] "
    else
        local cb=$(current_branch)
        if [ -n "$cb" ]; then
            REPO_CUSTOM_STATUS="$ZSH_THEME_GIT_PROMPT_PREFIX$(current_branch)$(parse_git_dirty)$ZSH_THEME_GIT_PROMPT_SUFFIX "
        fi
    fi

    PROMPT="$PS_USER_PART@%{$fg[$hostcolor]%}%m%{$reset_color%}:%j:%3d/ $REPO_CUSTOM_STATUS%T%# "
    export PROMPT
}
export SVN_EDITOR=vim

cl () { cd $1; ls }
